### ISSUE TITLE
Als een examen hebt ingevuld en een ander examen start dan is het al ingevuld met de gegevens van het vorige examen.

### ISSUE THREAD

**Issue by JWOverschot** [davinci-ao/examentool-client#2]
#### Welke Feature
- Als examinator wil ik een afnamen kunnen starten  
- Als examinator wil ik een criterium als zijnde (niet) waargenomen kunnen markeren  
- Als examinator wil ik een criterium als zijnde twijfelgeval kunnen markeren  

#### Waargenomen gedrag
Als je een examen start en alle stappen invult en dan een ander examen start dan is het tweede examen al ingevuld met de gegevens van het vorige examen.

#### Verwacht gedrag
Als je een nieuw examen start dat het nog niet ingevuld is of met eerder ingevoerde gegevens.

#### Bug reproduceren
1. Ga naar home.  
2. Klik op een examen.
3. Voer antwoorden bij het examen in.
4. Ga terug naar home.
5. Klik op een ander examen.

#### Verzie & Waarmee getest
OS: Windows 10
Browser: Chrome v. 70
Applicatie verzie: 0.1

**Comment by richard-boon** [comment]
Opgelost
