### ISSUE TITLE
Als een examen opnieuw wordt gestart dan komt er steeds een nieuw bij bij "inhaken op afnamen"

### ISSUE THREAD

**Issue by JWOverschot** [davinci-ao/examentool-client#4]
#### Welke Feature
- Als examinator wil ik een afnamen kunnen starten  
- Als examinator wil ik op een bestaande afnamen kunnen inhaken 

### Waargenomen gedrag
Als je een examen start en dan het examen nog een keer start dan wordt het examen niet uit het lijstje bij "inhaken op afnamen".

#### Verwacht gedrag
Dat een gestart examen maar een keer in de lijst op "inhaken op afnamen".

#### Bug reproduceren
1. Ga naar home.  
2. Klik op een examen.  
3. Ga terug naar home.  
4. Klik op hetzelfde examen.  
5. Ga naar "inhaken op afnamen".

#### Verzie & Waarmee getest
OS: Windows 10
Browser: Chrome v. 70
Applicatie verzie: 0.1

**Comment by richard-boon** [comment]
Dit is geen bug. Dit is normaal gedrag.
