### ISSUE TITLE
Als er veel examens zijn en niet meer op de pagina past wordt het afgesneden.

### ISSUE THREAD

**Issue by JWOverschot** [davinci-ao/examentool-client#5]
#### Welke Feature
- Als beheerder wil ik een examen kunnen toevoegen

#### Waargenomen gedrag
Als je veel examens hebt toegevoegd dan kan je niet naar onder scrollen om de onderste examen(s) te kunnen zien.
> Voorbeeld afbeelding ![examen app screen 1](https://user-images.githubusercontent.com/21358884/48400683-56c08b00-e727-11e8-8728-58fda025e97e.PNG)
> Uitgezoomde van vorige screenshot 
![examen app screen 2](https://user-images.githubusercontent.com/21358884/48400919-fa11a000-e727-11e8-9ea3-d754c64a7890.PNG)

#### Verwacht gedrag
Als er te veel examens zijn voor op de pagina dat je naar beneden kan scrollen.

#### Bug reproduceren
1. Ga naar "Add exam".
2. Voeg een examen toe.
3. Herhaal stap 1 en 2 tot dat je genoeg examens hebt om van de home pagina af te gaan.

#### Verzie & Waarmee getest
OS: Windows 10
Browser: Chrome v. 70
Applicatie verzie: 0.1

**Comment by richard-boon** [comment]
Opgelost
